// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package platform

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// GetBalance provides a mock function for the type MockClient
func (_mock *MockClient) GetBalance(ctx context.Context) (*Balance, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*Balance, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *Balance); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockClient_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) GetBalance(ctx interface{}) *MockClient_GetBalance_Call {
	return &MockClient_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx)}
}

func (_c *MockClient_GetBalance_Call) Run(run func(ctx context.Context)) *MockClient_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_GetBalance_Call) Return(balance *Balance, err error) *MockClient_GetBalance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockClient_GetBalance_Call) RunAndReturn(run func(ctx context.Context) (*Balance, error)) *MockClient_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetBillHistory provides a mock function for the type MockClient
func (_mock *MockClient) GetBillHistory(ctx context.Context, opts ...QueryOption) ([]BillRecord, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetBillHistory")
	}

	var r0 []BillRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...QueryOption) ([]BillRecord, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...QueryOption) []BillRecord); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BillRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...QueryOption) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetBillHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBillHistory'
type MockClient_GetBillHistory_Call struct {
	*mock.Call
}

// GetBillHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...QueryOption
func (_e *MockClient_Expecter) GetBillHistory(ctx interface{}, opts ...interface{}) *MockClient_GetBillHistory_Call {
	return &MockClient_GetBillHistory_Call{Call: _e.mock.On("GetBillHistory",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockClient_GetBillHistory_Call) Run(run func(ctx context.Context, opts ...QueryOption)) *MockClient_GetBillHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []QueryOption
		var variadicArgs []QueryOption
		if len(args) > 1 {
			variadicArgs = args[1].([]QueryOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClient_GetBillHistory_Call) Return(billRecords []BillRecord, err error) *MockClient_GetBillHistory_Call {
	_c.Call.Return(billRecords, err)
	return _c
}

func (_c *MockClient_GetBillHistory_Call) RunAndReturn(run func(ctx context.Context, opts ...QueryOption) ([]BillRecord, error)) *MockClient_GetBillHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetBuyHistory provides a mock function for the type MockClient
func (_mock *MockClient) GetBuyHistory(ctx context.Context, opts ...QueryOption) ([]TradeRecord, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetBuyHistory")
	}

	var r0 []TradeRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...QueryOption) ([]TradeRecord, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...QueryOption) []TradeRecord); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TradeRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...QueryOption) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetBuyHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBuyHistory'
type MockClient_GetBuyHistory_Call struct {
	*mock.Call
}

// GetBuyHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...QueryOption
func (_e *MockClient_Expecter) GetBuyHistory(ctx interface{}, opts ...interface{}) *MockClient_GetBuyHistory_Call {
	return &MockClient_GetBuyHistory_Call{Call: _e.mock.On("GetBuyHistory",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockClient_GetBuyHistory_Call) Run(run func(ctx context.Context, opts ...QueryOption)) *MockClient_GetBuyHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []QueryOption
		var variadicArgs []QueryOption
		if len(args) > 1 {
			variadicArgs = args[1].([]QueryOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClient_GetBuyHistory_Call) Return(tradeRecords []TradeRecord, err error) *MockClient_GetBuyHistory_Call {
	_c.Call.Return(tradeRecords, err)
	return _c
}

func (_c *MockClient_GetBuyHistory_Call) RunAndReturn(run func(ctx context.Context, opts ...QueryOption) ([]TradeRecord, error)) *MockClient_GetBuyHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetSellHistory provides a mock function for the type MockClient
func (_mock *MockClient) GetSellHistory(ctx context.Context, opts ...QueryOption) ([]TradeRecord, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetSellHistory")
	}

	var r0 []TradeRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...QueryOption) ([]TradeRecord, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...QueryOption) []TradeRecord); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]TradeRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...QueryOption) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetSellHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSellHistory'
type MockClient_GetSellHistory_Call struct {
	*mock.Call
}

// GetSellHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...QueryOption
func (_e *MockClient_Expecter) GetSellHistory(ctx interface{}, opts ...interface{}) *MockClient_GetSellHistory_Call {
	return &MockClient_GetSellHistory_Call{Call: _e.mock.On("GetSellHistory",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockClient_GetSellHistory_Call) Run(run func(ctx context.Context, opts ...QueryOption)) *MockClient_GetSellHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []QueryOption
		var variadicArgs []QueryOption
		if len(args) > 1 {
			variadicArgs = args[1].([]QueryOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockClient_GetSellHistory_Call) Return(tradeRecords []TradeRecord, err error) *MockClient_GetSellHistory_Call {
	_c.Call.Return(tradeRecords, err)
	return _c
}

func (_c *MockClient_GetSellHistory_Call) RunAndReturn(run func(ctx context.Context, opts ...QueryOption) ([]TradeRecord, error)) *MockClient_GetSellHistory_Call {
	_c.Call.Return(run)
	return _c
}

// Verify provides a mock function for the type MockClient
func (_mock *MockClient) Verify(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockClient_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockClient_Expecter) Verify(ctx interface{}) *MockClient_Verify_Call {
	return &MockClient_Verify_Call{Call: _e.mock.On("Verify", ctx)}
}

func (_c *MockClient_Verify_Call) Run(run func(ctx context.Context)) *MockClient_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_Verify_Call) Return(err error) *MockClient_Verify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Verify_Call) RunAndReturn(run func(ctx context.Context) error) *MockClient_Verify_Call {
	_c.Call.Return(run)
	return _c
}
