// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateAccount'](arg1, arg2, arg3);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetBillChartData(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBillChartData'](arg1, arg2, arg3);
}

export function GetBillRecords(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GetBillRecords'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetCompletedTrades(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetCompletedTrades'](arg1, arg2, arg3, arg4, arg5);
}

export function GetCompletedTradesSummary(arg1) {
  return window['go']['main']['App']['GetCompletedTradesSummary'](arg1);
}

export function GetDashboardSummary() {
  return window['go']['main']['App']['GetDashboardSummary']();
}

export function GetInventory(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['GetInventory'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetItemDetail(arg1, arg2) {
  return window['go']['main']['App']['GetItemDetail'](arg1, arg2);
}

export function GetMarketPrices() {
  return window['go']['main']['App']['GetMarketPrices']();
}

export function GetMonthlyBreakdown(arg1, arg2) {
  return window['go']['main']['App']['GetMonthlyBreakdown'](arg1, arg2);
}

export function GetPnlSummary(arg1) {
  return window['go']['main']['App']['GetPnlSummary'](arg1);
}

export function GetRentalHistory(arg1, arg2) {
  return window['go']['main']['App']['GetRentalHistory'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUnmatchedSells(arg1) {
  return window['go']['main']['App']['GetUnmatchedSells'](arg1);
}

export function SyncAccount(arg1) {
  return window['go']['main']['App']['SyncAccount'](arg1);
}

export function UpdateAccount(arg1) {
  return window['go']['main']['App']['UpdateAccount'](arg1);
}

export function UpdateAccountInfo(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateAccountInfo'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
